### ISSUE TITLE
Unable to generate correct output file

### ISSUE THREAD

**Issue by Auzel** [UT-SE-Research/ODRepair#1]
The results.csv has null values for polluter, time, polluted field for the tests supplied to the script.
I include the following two excerpts of the output when `runAll.sh data/test.csv` is ran, 

" Running ktuukkan/marine-api net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
find: gen_tests/marine-api: No such file or directory
NO GEN TESTS FOR net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
Enter debugging phase."

"rootScriptDir: /Users/<user_name>/SEResearch/NOD_Project/ODRepair/experiments/
pkg_filter_script: /Users/<user_name>/SEResearch/NOD_Project/ODRepair/experiments//package_finder.py
rootdir: /Users/<user_name>/SEResearch/NOD_Project/ODRepair/experiments
rootdir: /Users/<user_name>/SEResearch/NOD_Project/ODRepair/experiments
projDir: /Users/<user_name>/SEResearch/NOD_Project/ODRepair/experiments/xmls/ktuukkan/marine-api does not exist
rootProj /Users/<user_name>/SEResearch/NOD_Project/ODRepair/experiments/xmls/ktuukkan does not exist
xmlTestDir: /Users/<user_name>/SEResearch/NOD_Project/ODRepair/experiments/xmls/ktuukkan/marine-api/net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage does not exist"

How may I resolve this issue?

**Comment by ChopinLi-cp** [comment]
From the log, the problem is from the first phase. If you output null in the output/result.csv, it may mean the testrunner, iDFlakies and xstream ODRepair depends on have not been installed properly. Or the project have not been installed properly. There can be another issue like the pom.xml for the module of the marine-api is not changed. I think the run.py can automate this process and you do not need to clone the project by yourself. My guess is that you can try "bash pom-modify-ifixplus/modify-project.sh <path-to-marine-api> and try again.

**Comment by Auzel** [comment]
Okay thanks. I was able to fix that problem. I now receive another error
"*******************IFIXPLUS************************
Finished run_debugging_tools.sh
Fri Apr 22 12:30:13 CDT 2022
Traceback (most recent call last):
  File "run.py", line 834, in <module>
    runExp()
  File "run.py", line 769, in runExp
    all_cases = extractCasesInfo(EXP_CSV)
  File "run.py", line 111, in extractCasesInfo
    case['field_fqn'] = row[13]
IndexError: list index out of range
Fri Apr 22 12:30:13 CDT 2022 ===> Running ktuukkan/marine-api net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
find: gen_tests/marine-api: No such file or directory
NO GEN TESTS FOR net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
Enter debugging phase."

**Comment by ChopinLi-cp** [comment]
I am sorry for the inconvenience. It seems that the 13th column of the output/result.csv does not exist. Maybe you can check the last row of the  output/overall_results.csv, which contains the history results. If the 13th column is null, it should still be the problem of the first phase. You can check under repos/ if there are testrunner4iFixPlus/, idflakies4iFixPlus/, borrowState/ and reseter-finder/ and inside these repos if they are installed. And under projectsInstall/projects/ktuukkan/marine-api, if the pom.xml has been changed.

I think during the running process, you can check the temporary file output/result.csv to check if it outputs the necessary results.

Or maybe you can try to delete the ktuukkan/marine-api from the projectsInstall/projects and run it again.

**Comment by Auzel** [comment]
By modifying the pom.xml, do you mean adding the following lines?
```<plugin>
                <groupId>edu.illinois.cs</groupId>
                <artifactId>testrunner-maven-plugin</artifactId>
                <version>1.2-SNAPSHOT</version>
                <dependencies>
                    <dependency>
                        <groupId>edu.illinois.cs</groupId>
                        <artifactId>idflakies</artifactId>
                        <version>1.0.2</version>
                    </dependency>
                </dependencies>
            </plugin>
```
These lines already exist in the pom.xml. Three of the four repos you mentioned are present in repos/. Only reseter-finder/ could be found in the parent folder. I tried moving it inside the repos/ folder but the result is the same. I also tried deleting projectsInstall/projects/ktuukkan/marine-api and running it again. 

I'm not sure what you mean by 13th column in the overall_results.csv. Only 8 columns are present. For example, this is a line taken from the overall_results.csv file 

```ktuukkan/marine-api,af0003847db9ba822f67d4f1dceb8de3fe63250a,.,net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testConstructor,net.sf.marineapi.nmea.parser.SentenceFactoryTest.testRegisterParserWithAlternativeBeginChar,null,null,null```

**Comment by ChopinLi-cp** [comment]
Yes, I think this means the testrunner/iDFlakies is not installed from that output file. The 13th column is the polluted static field that is needed by the second phase. Maybe you can check the log/... file to see the log when running the tool. You can also share me with the log file.

**Comment by Auzel** [comment]
Log for net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< net.sf.marineapi:marineapi >---------------------
[INFO] Building Java Marine API 0.11.0-SNAPSHOT
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] >>> testrunner-maven-plugin:1.2-SNAPSHOT:testplugin (default-cli) > test-compile @ marineapi >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ marineapi ---
[INFO] Skipping Rule Enforcement.
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ marineapi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ marineapi ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ marineapi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 10 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ marineapi ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< testrunner-maven-plugin:1.2-SNAPSHOT:testplugin (default-cli) < test-compile @ marineapi <<<
[INFO] 
[INFO] 
[INFO] --- testrunner-maven-plugin:1.2-SNAPSHOT:testplugin (default-cli) @ marineapi ---
xmlFileName: 0
replyPath: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/jsonFiles_0/net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage/flaky-lists.json
module: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
tests!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
$$$$$$$$$$$testFailOrder_full: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
dtl!!!!!!!!!!!
testFailOrder_full1 : net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
phase 0 begin
$$$$$$$$$$$testFailOrder_full: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
dtl!!!!!!!!!!!
testFailOrder_full1 : net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
$$$$$$$$$$$testPassOrder_full: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
dtl!!!!!!!!!!!
testFailOrder_full1 : net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
$$$$$$$$$$$testFailOrder_full: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
dtl!!!!!!!!!!!
testFailOrder_full1 : net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testBasicListenerWithUnexpectedMessage
[ERROR] 
java.lang.Exception: Non-zero exit code (output in /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api/failing-test-output-1650656486522-7cf1a862-0b85-4547-8be7-a496031ee4ca): 1
    at edu.illinois.cs.testrunner.runner.Runner.$anonfun$runWithCp$3 (Runner.scala:75)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withProperties$2 (TempFiles.scala:38)
    at edu.illinois.cs.testrunner.util.autoClose.$anonfun$autoCloseTry$1 (autoClose.scala:7)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.autoClose.autoCloseTry (autoClose.scala:7)
    at edu.illinois.cs.testrunner.util.autoClose.apply (autoClose.scala:24)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withProperties$1 (TempFiles.scala:36)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withTempFile$1 (TempFiles.scala:17)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.TempFiles$.withTempFile (TempFiles.scala:17)
    at edu.illinois.cs.testrunner.util.TempFiles$.withProperties (TempFiles.scala:36)
    at edu.illinois.cs.testrunner.runner.Runner.$anonfun$runWithCp$2 (Runner.scala:50)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withTempFile$1 (TempFiles.scala:17)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.TempFiles$.withTempFile (TempFiles.scala:17)
    at edu.illinois.cs.testrunner.runner.Runner.$anonfun$runWithCp$1 (Runner.scala:49)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withSeq$1 (TempFiles.scala:31)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withTempFile$1 (TempFiles.scala:17)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.TempFiles$.withTempFile (TempFiles.scala:17)
    at edu.illinois.cs.testrunner.util.TempFiles$.withSeq (TempFiles.scala:25)
    at edu.illinois.cs.testrunner.runner.Runner.runWithCp (Runner.scala:48)
    at edu.illinois.cs.testrunner.runner.Runner.runWithCp$ (Runner.scala:47)
    at edu.illinois.cs.testrunner.runner.SmartRunner.runWithCp (SmartRunner.scala:22)
    at edu.illinois.cs.dt.tools.runner.InstrumentingSmartRunner.lambda$runWithCp$0 (InstrumentingSmartRunner.java:56)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withTempFile$1 (TempFiles.scala:17)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.TempFiles$.withTempFile (TempFiles.scala:17)
    at edu.illinois.cs.testrunner.util.TempFiles.withTempFile (TempFiles.scala)
    at edu.illinois.cs.dt.tools.runner.InstrumentingSmartRunner.runWithCp (InstrumentingSmartRunner.java:52)
    at edu.illinois.cs.testrunner.runner.Runner.run (Runner.scala:33)
    at edu.illinois.cs.testrunner.runner.Runner.run$ (Runner.scala:33)
    at edu.illinois.cs.testrunner.runner.SmartRunner.run (SmartRunner.scala:29)
    at edu.illinois.cs.testrunner.runner.Runner.runList (Runner.scala:28)
    at edu.illinois.cs.testrunner.runner.Runner.runList$ (Runner.scala:27)
    at edu.illinois.cs.testrunner.runner.SmartRunner.runList (SmartRunner.scala:22)
    at edu.illinois.cs.dt.tools.utility.iFixPlusPlugin.execute (iFixPlusPlugin.java:152)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at edu.illinois.cs.testrunner.mavenplugin.TestPluginPlugin.execute (TestPluginPlugin.scala:59)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.588 s
[INFO] Finished at: 2022-04-22T14:41:26-05:00
[INFO] ------------------------------------------------------------------------
```

Log for net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testConstructor

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< net.sf.marineapi:marineapi >---------------------
[INFO] Building Java Marine API 0.11.0-SNAPSHOT
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] >>> testrunner-maven-plugin:1.2-SNAPSHOT:testplugin (default-cli) > test-compile @ marineapi >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ marineapi ---
[INFO] Skipping Rule Enforcement.
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ marineapi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ marineapi ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ marineapi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 10 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ marineapi ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< testrunner-maven-plugin:1.2-SNAPSHOT:testplugin (default-cli) < test-compile @ marineapi <<<
[INFO] 
[INFO] 
[INFO] --- testrunner-maven-plugin:1.2-SNAPSHOT:testplugin (default-cli) @ marineapi ---
xmlFileName: 0
replyPath: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/jsonFiles_0/net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testConstructor/flaky-lists.json
module: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
tests!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
$$$$$$$$$$$testFailOrder_full: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
dtl!!!!!!!!!!!
testFailOrder_full1 : net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testConstructor
phase 0 begin
$$$$$$$$$$$testFailOrder_full: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
dtl!!!!!!!!!!!
testFailOrder_full1 : net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testConstructor
$$$$$$$$$$$testPassOrder_full: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
dtl!!!!!!!!!!!
testFailOrder_full1 : net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testConstructor
$$$$$$$$$$$testFailOrder_full: /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api
dtl!!!!!!!!!!!
testFailOrder_full1 : net.sf.marineapi.ais.event.AbstractAISMessageListenerTest.testConstructor
[ERROR] 
java.lang.Exception: Non-zero exit code (output in /Users/philmonroberts/SEResearch/NOD_Project/ODRepair/experiments/projectsInstall/projects/ktuukkan/marine-api/failing-test-output-1650656494299-94c98912-f7fa-42aa-b68e-84677b1d8c89): 1
    at edu.illinois.cs.testrunner.runner.Runner.$anonfun$runWithCp$3 (Runner.scala:75)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withProperties$2 (TempFiles.scala:38)
    at edu.illinois.cs.testrunner.util.autoClose.$anonfun$autoCloseTry$1 (autoClose.scala:7)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.autoClose.autoCloseTry (autoClose.scala:7)
    at edu.illinois.cs.testrunner.util.autoClose.apply (autoClose.scala:24)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withProperties$1 (TempFiles.scala:36)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withTempFile$1 (TempFiles.scala:17)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.TempFiles$.withTempFile (TempFiles.scala:17)
    at edu.illinois.cs.testrunner.util.TempFiles$.withProperties (TempFiles.scala:36)
    at edu.illinois.cs.testrunner.runner.Runner.$anonfun$runWithCp$2 (Runner.scala:50)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withTempFile$1 (TempFiles.scala:17)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.TempFiles$.withTempFile (TempFiles.scala:17)
    at edu.illinois.cs.testrunner.runner.Runner.$anonfun$runWithCp$1 (Runner.scala:49)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withSeq$1 (TempFiles.scala:31)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withTempFile$1 (TempFiles.scala:17)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.TempFiles$.withTempFile (TempFiles.scala:17)
    at edu.illinois.cs.testrunner.util.TempFiles$.withSeq (TempFiles.scala:25)
    at edu.illinois.cs.testrunner.runner.Runner.runWithCp (Runner.scala:48)
    at edu.illinois.cs.testrunner.runner.Runner.runWithCp$ (Runner.scala:47)
    at edu.illinois.cs.testrunner.runner.SmartRunner.runWithCp (SmartRunner.scala:22)
    at edu.illinois.cs.dt.tools.runner.InstrumentingSmartRunner.lambda$runWithCp$0 (InstrumentingSmartRunner.java:56)
    at edu.illinois.cs.testrunner.util.TempFiles$.$anonfun$withTempFile$1 (TempFiles.scala:17)
    at scala.util.Try$.apply (Try.scala:209)
    at edu.illinois.cs.testrunner.util.TempFiles$.withTempFile (TempFiles.scala:17)
    at edu.illinois.cs.testrunner.util.TempFiles.withTempFile (TempFiles.scala)
    at edu.illinois.cs.dt.tools.runner.InstrumentingSmartRunner.runWithCp (InstrumentingSmartRunner.java:52)
    at edu.illinois.cs.testrunner.runner.Runner.run (Runner.scala:33)
    at edu.illinois.cs.testrunner.runner.Runner.run$ (Runner.scala:33)
    at edu.illinois.cs.testrunner.runner.SmartRunner.run (SmartRunner.scala:29)
    at edu.illinois.cs.testrunner.runner.Runner.runList (Runner.scala:28)
    at edu.illinois.cs.testrunner.runner.Runner.runList$ (Runner.scala:27)
    at edu.illinois.cs.testrunner.runner.SmartRunner.runList (SmartRunner.scala:22)
    at edu.illinois.cs.dt.tools.utility.iFixPlusPlugin.execute (iFixPlusPlugin.java:152)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at edu.illinois.cs.testrunner.mavenplugin.TestPluginPlugin.execute (TestPluginPlugin.scala:59)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:127)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.626 s
[INFO] Finished at: 2022-04-22T14:41:34-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by ChopinLi-cp** [comment]
Thank you for sharing. 

The output shows that the iDFlakies and the project have been installed properly. From the log, it seems it is a problem from the testrunner and it shows testrunner encounters problems when running the failing order. Does the testrunner on your machine run properly when using normal iDFlakies or at the right branch testrunnner4iFixPlus? Maybe you can also share me with file ktuukkan/marine-api/failing-test-output-1650656494299-94c98912-f7fa-42aa-b68e-84677b1d8c89.

**Comment by Auzel** [comment]
Log for ktuukkan/marine-api/failing-test-output-1650656494299-94c98912-f7fa-42aa-b68e-84677b1d8c89

```
Failed to find Premain-Class manifest attribute in /Users/philmonroberts/.m2/repository/edu/illinois/cs/testrunner-running/1.3-SNAPSHOT/testrunner-running-1.3-SNAPSHOT.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

Note the `.jar` file does exist in the location.
